// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PDFShelf.Api.Data;

#nullable disable

namespace PDFShelf.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251109085809_UpdateAddStorageMBToUser")]
    partial class UpdateAddStorageMBToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PDFShelf.Api.Models.PdfFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId1")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId2")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId3")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.HasIndex("UserId2");

                    b.HasIndex("UserId3");

                    b.ToTable("PdfFile");
                });

            modelBuilder.Entity("PDFShelf.Api.Models.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanAnnotate")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanShare")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<double?>("MonthlyPrice")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("StorageLimitMB")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Plans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CanAnnotate = true,
                            CanShare = false,
                            IsActive = true,
                            Name = "Free",
                            StorageLimitMB = 30.0
                        },
                        new
                        {
                            Id = 2,
                            CanAnnotate = true,
                            CanShare = true,
                            IsActive = true,
                            MonthlyPrice = 19.899999999999999,
                            Name = "Basic",
                            StorageLimitMB = 200.0
                        },
                        new
                        {
                            Id = 3,
                            CanAnnotate = true,
                            CanShare = true,
                            IsActive = true,
                            MonthlyPrice = 39.899999999999999,
                            Name = "Premium",
                            StorageLimitMB = 1000.0
                        });
                });

            modelBuilder.Entity("PDFShelf.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PlanId")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("UsedStorageMB")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PlanId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PDFShelf.Api.Models.PdfFile", b =>
                {
                    b.HasOne("PDFShelf.Api.Models.User", null)
                        .WithMany("Annotations")
                        .HasForeignKey("UserId");

                    b.HasOne("PDFShelf.Api.Models.User", null)
                        .WithMany("Pdfs")
                        .HasForeignKey("UserId1");

                    b.HasOne("PDFShelf.Api.Models.User", null)
                        .WithMany("SharesGiven")
                        .HasForeignKey("UserId2");

                    b.HasOne("PDFShelf.Api.Models.User", null)
                        .WithMany("SharesReceived")
                        .HasForeignKey("UserId3");
                });

            modelBuilder.Entity("PDFShelf.Api.Models.User", b =>
                {
                    b.HasOne("PDFShelf.Api.Models.Plan", "Plan")
                        .WithMany("Users")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("PDFShelf.Api.Models.Plan", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("PDFShelf.Api.Models.User", b =>
                {
                    b.Navigation("Annotations");

                    b.Navigation("Pdfs");

                    b.Navigation("SharesGiven");

                    b.Navigation("SharesReceived");
                });
#pragma warning restore 612, 618
        }
    }
}
